name: Build and Test

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
      - dev
  workflow_dispatch:
    inputs:
      release:
        description: 'Make release'

jobs:
  build:
    name: Building on ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - build: linux-amd64
            os: ubuntu-latest
            runtime_library: ovmwasm
            artifact_name: 'onyx-linux-ovm-amd64'
          - build: linux-amd64
            os: ubuntu-latest
            runtime_library: wasmer
            artifact_name: 'onyx-linux-wasmer-amd64'
          - build: linux-amd64
            os: ubuntu-latest
            runtime_library: none
            artifact_name: 'onyx-linux-none-amd64' 
          - build: darwin-arm64
            os: macos-11.0
            runtime_library: none
            target: aarch64-apple-darwin
            artifact_name: 'onyx-darwin-none-arm64'
          - build: darwin-amd64
            os: macos-11.0
            runtime_library: none
            artifact_name: 'onyx-darwin-none-amd64'
          # - build: darwin-arm64
          #   os: macos-11.0
          #   runtime_library: wasmer 
          #   artifact_name: 'onyx-darwin-wasmer-arm64'
          - build: windows-amd64
            os: windows-latest
            artifact_name: 'onyx-windows-wasmer-amd64'
    steps:
      - uses: actions/checkout@v3
      - name: Setup directory for building
        if: matrix.build == 'linux-amd64'
        run: |
          chmod +x build.sh
          mkdir -p build

      - name: Install Linux building dependencies
        if: matrix.runtime_library == 'wasmer'
        run: |
          curl https://get.wasmer.io -sSfL | sh
          echo "$HOME/.wasmer/bin" >> $GITHUB_PATH

      - name: Install Windows building dependencies
        if: matrix.build == 'windows-amd64'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build Onyx for ${{ matrix.build }}
        if: (matrix.build == 'linux-amd64') && (matrix.runtime_library != 'none')
        run: |
          ./build.sh compile package
        env:
          ONYX_CC: gcc
          ONYX_ARCH: linux_x86_64
          ONYX_RUNTIME_LIBRARY: ${{ matrix.runtime_library }} 
          ONYX_USE_DYNCALL: '1'
          
      - name: Build Onyx for ${{ matrix.build }}
        if: (matrix.build == 'linux-amd64') && (matrix.runtime_library == 'none')
        run: |
          ./build.sh compile package
        env:
          ONYX_CC: gcc
          ONYX_ARCH: linux_x86_64

      - name: Build Onyx for ${{ matrix.build }}
        if: (matrix.build == 'darwin-arm64') && (matrix.runtime_library == 'none')
        run: |
          ./build.sh compile package
        env:
          ONYX_CC: gcc
          ONYX_ARCH: darwin_arm64
          ONYX_TARGET: aarch64-apple-darwin

      - name: Build Onyx for ${{ matrix.build }}
        if: matrix.build == 'windows-amd64'
        run: |
          cmd.exe /c 'build.bat dist'
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.artifact_name }}
          path: dist
          if-no-files-found: error
          retention-days: 5