name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: add build folder
      run: mkdir build
    - name: make
      run: make
    - name: ./onyx progs/odin_example.onyx
      run: ./onyx progs/odin_example.onyx
